### ISSUE TITLE
SDXL Controlnet depth map output 

### ISSUE THREAD

**Issue by woodwardj** [LucianoCirino/efficiency-nodes-comfyui#139]
I am trying to use depth map controlnet with SDXL.  The output looks like a bright color version of the depth map in SDXL, works fine in SD15 or using WAS Nodes

Example Output: https://imgur.com/a/2J83ZAL

[sdxl_controlnet_efficiency_issue_workflow.json.txt](https://github.com/LucianoCirino/efficiency-nodes-comfyui/files/12506669/sdxl_controlnet_efficiency_issue_workflow.json.txt)

**Comment by LucianoCirino** [comment]
I have replicated the issue. Will investigate.

**Comment by LucianoCirino** [comment]
This issue is now resolved by commit https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/145/commits/a468ffd7a2d72bb8f63f4d0e83f6ef63acac2e02.
The issue was that in order to properly use the base ComfyUI ControlNetApply (Advanced) node, you **_must_** feed both the positive and negative conditionings (which I was not doing)

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/3b70c3a8-c365-4681-96a8-34c0c97c9ce3)

ControlNet Regular:
![ComfyUI_temp_ejdxc_00013_](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/9b6f0811-6977-4142-bdc1-2caa80c7c3fd)

ControlNet Stack:
![ComfyUI_temp_pkprd_00016_](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/8e0ef706-f6ef-4131-9d42-47eac66e762e)
