### ISSUE TITLE
The effect of 'cnet_stack' is not correct

### ISSUE THREAD

**Issue by mijuku233** [LucianoCirino/efficiency-nodes-comfyui#144]
After loading controllnet using 'cnet_stack', the generated image is very poor。

**Comment by LucianoCirino** [comment]
This issue is now resolved by commit https://github.com/LucianoCirino/efficiency-nodes-comfyui/pull/145/commits/a468ffd7a2d72bb8f63f4d0e83f6ef63acac2e02.
The issue was that in order to properly use the base ComfyUI ControlNetApply (Advanced) node, you **_must_** feed both the positive and negative conditionings (which I was not doing)

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/3b70c3a8-c365-4681-96a8-34c0c97c9ce3)

ControlNet Regular:
![ComfyUI_temp_ejdxc_00013_](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/9b6f0811-6977-4142-bdc1-2caa80c7c3fd)

ControlNet Stack:
![ComfyUI_temp_pkprd_00016_](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/8e0ef706-f6ef-4131-9d42-47eac66e762e)

**Comment by mijuku233** [comment]
> 此问题现已通过提交[a468ffd](https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/a468ffd7a2d72bb8f63f4d0e83f6ef63acac2e02)解决。 问题是，为了正确使用基本 ComfyUI ControlNetApply（高级）节点，您**_必须_**同时提供正条件和负条件（我没有这样做）
> 
> ![图像](https://user-images.githubusercontent.com/112517630/265781645-3b70c3a8-c365-4681-96a8-34c0c97c9ce3.png)
> 
> ControlNet 常规： ![ComfyUI_temp_ejdxc_00013_](https://user-images.githubusercontent.com/112517630/265782183-9b6f0811-6977-4142-bdc1-2caa80c7c3fd.png)
> 
> 控制网络堆栈： ![ComfyUI_temp_pkprd_00016_](https://user-images.githubusercontent.com/112517630/265782225-8e0ef706-f6ef-4131-9d42-47eac66e762e.png)

Only the first one will take effect, and subsequent 'cnet_stack' will not take effect

**Comment by mijuku233** [comment]
@LucianoCirino Only the first one will take effect, and subsequent 'cnet_stack' will not take effect

**Comment by mijuku233** [comment]
@LucianoCirino  Additionally, 'XY Input: Control Net' cannot run

**Comment by LucianoCirino** [comment]
Fixed by commit ->https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/8cb207b539d4456c248a251908e1e27ba95496f0

# ControlNet Stack Application Fix:
<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/f436d9d7-9aa9-4a4d-882d-a8bc93a7b848" width="720" alt="stack(overview)">
<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/c1440908-d53c-495c-a79b-424eebdd60d3" width="320" alt="stack">

# XY Input: Control Net Fix
## Strength
<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/c8b72e9b-4004-4ff0-ac25-7b2db1ca14b1" width="720" alt="strength(overview)">
<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/fc5872ec-14b6-4304-8360-fc958aaa28d6" width="320" alt="strength">

# Start%
<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/e55b9a0d-87d1-4785-b787-86faa8fc1b52" width="720" alt="start_pct(overview)">
<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/8154f5d2-e41f-4073-856d-d2157b53b47a" width="320" alt="start_pct">

# End%
<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/4d489e15-9f64-43a1-821d-d4e925bf5bcc" width="720" alt="end_pct(overview)">
<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/88789f47-a03a-4829-87cf-8ba5f9531845" width="320" alt="end_pct">

**Comment by mijuku233** [comment]
@LucianoCirino It's a little pity that two different 'XY Input: Control' cannot be input to X and Y at the same time.
Maybe it won't be easy to achieve? If yes, please ignore this small issue.
You did a great job! Thanks so much for your custom node!

**Comment by LucianoCirino** [comment]
> @LucianoCirino It's a little pity that two different 'XY Input: Control' cannot be input to X and Y at the same time. Maybe it won't be easy to achieve? If yes, please ignore this small issue. You did a great job! Thanks so much for your custom node!

Hey @mijuku233 what are you trying to accomplish? For XY plotting multiple ControlNet parameters, I recommend you use the '**XY Input: ControlNet Plot**' node.

**Comment by mijuku233** [comment]
> > @LucianoCirino It's a little pity that two different 'XY Input: Control' cannot be input to X and Y at the same time. Maybe it won't be easy to achieve? If yes, please ignore this small issue. You did a great job! Thanks so much for your custom node!
> 
> Hey @mijuku233 what are you trying to accomplish? For XY plotting multiple ControlNet parameters at the same time, I recommend you use the '**XY Input: ControlNet Plot**' node.

@LucianoCirino For example, X enters ControlNet-lineart and Y enters ControlNet-tile.
But it's a trivial improvement, not very useful, and it's okay to ignore it.
