### ISSUE TITLE
Updated pack, now Evaluate Integer node won't work

### ISSUE THREAD

**Issue by VikingTechLLC** [LucianoCirino/efficiency-nodes-comfyui#76]
Created an image2image workflow which automatically adjusts steps across multiple ksamplers using the evaluateinteger node.  Everything worked great, uploaded flow to CivitAI, over 130 downloads.
Tonight went to do more work on it, updated everything (been a few weeks since last doing that), and now the first evaluateinteger node in line is throwing this error.
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/84103587/52b0c8a3-7de6-45cb-8702-77d1d57c85b1)
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/84103587/92337aee-ccd5-4e93-8898-56e9adb4b02a)

**Comment by VikingTechLLC** [comment]
First updated via Manager extension.
That broke it initially. 

Then updated via git pull.
Didn't resolve.

Then updated via civitai download and zip extract and replaced files.
That fixed it

**Comment by LucianoCirino** [comment]
When ComfyUI manager installs nodes, it is grabbing the most up to date changes because it is installing straight from the Github repo. If your workflow has custom nodes from an older version, updating them will likely cause these types of errors without some **manual** work involved. What you would do is install via ComfyUI manager, then for every node that craps out, you manually grab a **new** fresh version of the node from the library (example: Efficiency Nodes -> Samplers -> KSampler (Efficient)), delete the one giving errors, and reconnect the new fresh node in its place.

There are ways to have this operation automatically done but that requires work from my end I never got around to implementing.
